### ISSUE TITLE
Email verification

### ISSUE THREAD

**Issue by harish** [JoshuaKGoldberg/Bookswap#79] opened 2014-03-28 18:47 UTC
Need to verify emails on sign up. This will be necessary in the future when attempting to merge accounts created with different login flows.

**Comment by JoshuaKGoldberg** [comment] 2014-03-31 17:26
Duplicate of https://github.com/Diogenesthecynic/Bookswap/issues/58

**Closed as completed by JoshuaKGoldberg** 2014-03-31 17:26 UTC
Labels: large, PHP, feature
