### ISSUE TITLE
User sign up is an annoying process

### ISSUE THREAD

**Issue by harish** [JoshuaKGoldberg/Bookswap#77] opened 2014-03-28 17:53 UTC
Should specify all password requirements alongside the password field, not just when you don't fulfill one. Especially when requirements are that strict.

**Comment by JoshuaKGoldberg** [comment] 2014-03-29 11:27
Fixed by https://github.com/Diogenesthecynic/Bookswap/commit/89bfefcad4f4e90af7273b51410d34eaabe89d0c and duplicate of https://github.com/Diogenesthecynic/Bookswap/issues/73

**Closed as completed by JoshuaKGoldberg** 2014-03-29 11:27 UTC
Labels: small, feature
